/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root endpoint
         * @description Returns a welcome message or serves the main web interface
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Welcome message or HTML interface */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "text/html": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/about": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get device information
         * @description Returns basic information about the clock device including model, type, and firmware version
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Device information */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description The firmware variant/model
                             * @example CLOCK-V1
                             */
                            model: string;
                            /**
                             * @description The device type
                             * @example clock
                             */
                            type: string;
                            /**
                             * @description The specific clock implementation
                             * @example nixie
                             * @enum {string}
                             */
                            subtype: "nixie" | "fibonacci" | "wordclock";
                            /**
                             * @description Firmware version
                             * @example 1.0.0
                             */
                            version: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get system configuration
         * @description Returns current system configuration including timezone, NTP server, and hostname settings
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current system configuration */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SystemConfig"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Update system configuration
         * @description Updates system configuration settings for timezone, NTP server, and hostname
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SystemConfigUpdate"];
                };
            };
            responses: {
                /** @description Configuration updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example success */
                            status?: string;
                        };
                    };
                };
                /** @description Invalid JSON format or parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Request timeout */
                408: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/time/zonedb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get available timezones
         * @description Returns a list of all available timezone names and rules from the embedded timezone database
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of available timezones */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Timezone name
                             * @example America/New_York
                             */
                            name: string;
                            /**
                             * @description Timezone rule string
                             * @example EST5EDT,M3.2.0,M11.1.0
                             */
                            rule: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/led/effects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available LED effects
         * @description Returns a list of all available LED effects that can be applied to LED channels. Not available on fibonacci devices.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of available effects */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Human-readable effect name
                             * @example Breathe
                             */
                            name: string;
                            /**
                             * @description Effect identifier for API calls
                             * @example BREATHE
                             */
                            id: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/led/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get LED channel configuration
         * @description Returns information about available LED channels and their properties. Not available on fibonacci devices.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description LED channel configuration */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            channels: {
                                /**
                                 * @description Channel index number
                                 * @example 0
                                 */
                                index: number;
                                /**
                                 * @description Number of LEDs in this channel
                                 * @example 60
                                 */
                                num_leds: number;
                                /**
                                 * @description LED type
                                 * @example RGB
                                 * @enum {string}
                                 */
                                type: "RGB" | "RGBW";
                                /**
                                 * @description Channel name
                                 * @example Backlight
                                 */
                                name: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/led/channel/{channelIndex}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get LED channel state
         * @description Returns the current configuration and state of a specific LED channel. Not available on fibonacci devices.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The LED channel index */
                    channelIndex: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description LED channel state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LEDChannelState"];
                    };
                };
                /** @description Invalid channel index */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Channel not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Configure LED channel
         * @description Updates the configuration of a specific LED channel including color, brightness, effect, and power state. Not available on fibonacci devices.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The LED channel index */
                    channelIndex: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LEDChannelConfig"];
                };
            };
            responses: {
                /** @description Updated LED channel state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LEDChannelState"];
                    };
                };
                /** @description Invalid channel index or JSON format */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Channel not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nixie": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get nixie configuration
         * @description Returns the current configuration of the nixie tubes including brightness, time format, and other settings. Only available on nixie devices.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current nixie configuration */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NixieConfig"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Update nixie configuration
         * @description Updates the nixie tube configuration including brightness, time format, blinking dots, and power state. Only available on nixie devices.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NixieConfigUpdate"];
                };
            };
            responses: {
                /** @description Updated nixie configuration */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NixieConfig"];
                    };
                };
                /** @description Invalid JSON format or configuration parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Request timeout */
                408: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fibonacci": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get fibonacci configuration
         * @description Returns the current configuration of the fibonacci clock including brightness, theme, and power state. Also includes available themes. Only available on fibonacci devices.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current fibonacci configuration with available themes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FibonacciConfig"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Update fibonacci configuration
         * @description Updates the fibonacci clock configuration including brightness, theme selection, and power state. Only available on fibonacci devices.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FibonacciConfigUpdate"];
                };
            };
            responses: {
                /** @description Updated fibonacci configuration (includes available themes) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FibonacciConfig"];
                    };
                };
                /** @description Invalid JSON format or configuration parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Request timeout */
                408: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SystemConfig: {
            /**
             * @description Whether automatic timezone detection is enabled
             * @example false
             */
            auto_timezone: boolean;
            /**
             * @description Current timezone identifier
             * @example America/New_York
             */
            timezone: string;
            /**
             * @description NTP server address for time synchronization
             * @example pool.ntp.org
             */
            ntp_server: string;
            /**
             * @description WiFi hostname of the device
             * @example kd-clock-001
             */
            wifi_hostname: string;
        };
        /** @description All fields are optional. Only provided fields will be updated. */
        SystemConfigUpdate: {
            /** @description Enable/disable automatic timezone detection */
            auto_timezone?: boolean;
            /** @description Timezone identifier to set */
            timezone?: string;
            /** @description NTP server address */
            ntp_server?: string;
            /** @description WiFi hostname (1-63 characters) */
            wifi_hostname?: string;
        };
        Color: {
            /** @description Red component */
            r: number;
            /** @description Green component */
            g: number;
            /** @description Blue component */
            b: number;
            /** @description White component (RGBW channels only) */
            w?: number;
        };
        LEDChannelState: {
            /**
             * @description Current effect identifier
             * @example SOLID
             */
            effect_id: string;
            /**
             * @description Channel brightness
             * @example 255
             */
            brightness: number;
            /**
             * @description Effect speed parameter
             * @example 50
             */
            speed: number;
            /**
             * @description Whether the channel is enabled
             * @example true
             */
            on: boolean;
            color: components["schemas"]["Color"];
        };
        /** @description All fields are optional. Only provided fields will be updated. */
        LEDChannelConfig: {
            /**
             * @description Effect identifier to apply
             * @example BREATHE
             */
            effect_id?: string;
            /** @description Channel brightness */
            brightness?: number;
            /** @description Effect speed parameter */
            speed?: number;
            /** @description Enable/disable the channel */
            on?: boolean;
            color?: components["schemas"]["Color"];
        };
        NixieConfig: {
            /**
             * @description Nixie tube brightness percentage
             * @example 50
             */
            brightness: number;
            /**
             * @description Use 24-hour format (true) or 12-hour format (false)
             * @example false
             */
            military_time: boolean;
            /**
             * @description Enable blinking separator dots
             * @example true
             */
            blinking_dots: boolean;
            /**
             * @description Whether the nixie tubes are powered on
             * @example true
             */
            on: boolean;
        };
        /** @description All fields are optional. Only provided fields will be updated. */
        NixieConfigUpdate: {
            /** @description Nixie tube brightness percentage */
            brightness?: number;
            /** @description Use 24-hour format (true) or 12-hour format (false) */
            military_time?: boolean;
            /** @description Enable blinking separator dots */
            blinking_dots?: boolean;
            /** @description Power state of the nixie tubes */
            on?: boolean;
        };
        FibonacciTheme: {
            /**
             * @description Theme identifier
             * @example 0
             */
            id: number;
            /**
             * @description Theme name
             * @example RGB
             */
            name: string;
            /**
             * @description Color for hour segments (hex format)
             * @example #FF0000
             */
            hour_color: string;
            /**
             * @description Color for minute segments (hex format)
             * @example #00FF00
             */
            minute_color: string;
            /**
             * @description Color for segments showing both hour and minute (hex format)
             * @example #0000FF
             */
            both_color: string;
        };
        FibonacciConfig: {
            /**
             * @description LED brightness
             * @example 255
             */
            brightness: number;
            /**
             * @description Currently selected theme ID
             * @example 0
             */
            theme_id: number;
            /**
             * @description Whether the fibonacci clock is powered on
             * @example true
             */
            on: boolean;
            /** @description Available color themes */
            themes: components["schemas"]["FibonacciTheme"][];
        };
        /** @description All fields are optional. Only provided fields will be updated. */
        FibonacciConfigUpdate: {
            /** @description LED brightness */
            brightness?: number;
            /** @description Theme ID to select */
            theme_id?: number;
            /** @description Power state of the fibonacci clock */
            on?: boolean;
        };
    };
    responses: {
        /** @description Bad request - invalid parameters or JSON format */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description Internal server error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description Request timeout */
        RequestTimeout: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
